zebraproject/zebraproject/urls.py
from django.contrib import admin
from django.urls import path
from zebraapp import views
from django.conf import settings
from django.conf.urls.static import static
import accounts.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.main, name ="main"),
    path('login/',accounts.views.login, name = 'main-login'),
    path('logout/',accounts.views.logout, name = 'logout'),
    path('signup/',accounts.views.signup, name = 'signup'),
    path('product/<int:category_id>/', views.show_product, name='product'),
    path('childproduct/<int:product_id>/', views.show_childproduct, name = 'childproduct'),
    path('mypage/', views.show_myPage, name = 'mypage'),
    path('mypage/submit_myItem', views.submit_myItem_in_myPage, name = 'submit_myItem_pop'),
    path('mypage/create_myItem', views.create_myItem_in_myPage, name = 'create_myItem'),
    path('mypage/<int:my_Items_id>', views.detail_myItem_in_myPage, name = 'detail_myItem'),
    path('mypage/<int:my_Items_id>/update_myItem', views.update_myItem_in_myPage, name = 'update_myItem'),
    path('mypage/<int:my_Items_id>/delete_myItem', views.delete_myItem_in_myPage, name = 'delete_myItem'),
    path('likeCart/', views.likeCart, name="likeCart"),
    path('delete/<int:childproduct_id>/', views.delete_like, name='delete_like'),
    path('tip/',views.tip, name ="tip"),
    path('tip/<int:tip_id>',views.tip_detail, name ="tip_detail"),
    path('childproduct/<int:childproduct_id>/like',views.like, name ="productlike"),
    path('childproduct/1/login/', accounts.views.login, name ='login'),
    path('childproduct/2/login/', accounts.views.login, name ='login'),
    path('childproduct/3/login/', accounts.views.login, name ='login'),
    path('childproduct/4/login/', accounts.views.login, name ='login'),
    path('childproduct/5/login/', accounts.views.login, name ='login'),
    path('childproduct/6/login/', accounts.views.login, name ='login'),
    path('childproduct/7/login/', accounts.views.login, name ='login'),
    path('childproduct/8/login/', accounts.views.login, name ='login'),
    path('childproduct/9/login/', accounts.views.login, name ='login'),
    path('childproduct/10/login/', accounts.views.login, name ='login'),
    path('childproduct/11/login/', accounts.views.login, name ='login'),
    path('childproduct/12/login/', accounts.views.login, name ='login'),
    path('childproduct/13/login/', accounts.views.login, name ='login'),
    path('childproduct/14/login/', accounts.views.login, name ='login'),
    path('childproduct/15/login/', accounts.views.login, name ='login'),
    path('childproduct/16/login/', accounts.views.login, name ='login'),
    path('childproduct/17/login/', accounts.views.login, name ='login'),
    path('childproduct/18/login/', accounts.views.login, name ='login'),
    path('childproduct/19/login/', accounts.views.login, name ='login'),
    path('childproduct/20/login/', accounts.views.login, name ='login'),
    path('childproduct/21/login/', accounts.views.login, name ='login'),
    path('childproduct/22/login/', accounts.views.login, name ='login'),
    path('childproduct/23/login/', accounts.views.login, name ='login'),
    path('childproduct/24/login/', accounts.views.login, name ='login'),
        
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

zebraproject/zebraapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Category(models.Model):
    sort = models.CharField(max_length=255)

    def __str__(self):
        return '{}'.format(self.sort)


class Product(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product_category')
    image = models.ImageField(upload_to='images/')
    detail = models.TextField(null=True)
    pub_date = models.DateTimeField(auto_now_add = True, null=True)

    def __str__(self):
        return '{}'.format(self.name)


class ChildProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null =True)
    name = models.CharField(max_length=200,null=True)
    price = models.IntegerField()
    shopName = models.CharField(max_length=200, null=True)
    shopLink = models.TextField(null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    ship = models.CharField(max_length = 255 , null = True)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return '{}'.format(self.name)

class MyItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_myitem')
    itemName = models.CharField(max_length=200)
    itemShop = models.CharField(max_length=200)
    itemDate = models.DateField('date published')
    
    class Meta:
        ordering = ['-itemDate']

    def __str__(self):
        return self.itemDate.strftime("%Y.%m.%d") + "-" + self.itemName + "-" + self.itemShop

class Tip(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateField('date published')
    cover = models.ImageField(upload_to="images")

    def __str__(self):
        return self.title

class TipBody(models.Model):
    tip = models.ForeignKey(Tip, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    body = models.TextField()

class Likes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_like')
    product = models.ForeignKey(ChildProduct, on_delete=models.CASCADE, related_name='product_likes')
    quantity = models.IntegerField(default=0)
    

zebraproject/zebraapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category, Product, ChildProduct, MyItem, Tip, TipBody, Likes
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.contrib import messages
from django.db.models import F
import json
from django.http import JsonResponse
import operator
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied

# Create your views here.
def main(request):
    userCount = User.objects.all().count()
    userCount = userCount + 12560
    return render(request,'main.html', {'userCount' : userCount})


def show_product(request, category_id):
    categories = Category.objects.all()
    category = Category.objects.get(pk=category_id)
    products = Product.objects.filter(category=category).order_by('pub_date')
    paginator = Paginator(products, 12)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    
    return render(request, 'product.html', {'category': category, 'categories': categories ,'posts' : posts})


def show_childproduct(request, product_id):
    product = get_object_or_404(Product, pk = product_id)
    childproducts = ChildProduct.objects.filter(product=product_id)
    likes = {}
    likeCnt = 0
    if request.user.is_authenticated:
        likes = Likes.objects.filter(user=request.user)
        likeCnt = Likes.objects.filter(user=request.user).count()
        for like in likes:
            for child in childproducts:
                if child.id == like.product.id:
                    child.likes = 1

    return render(request,'childproduct.html' , {'product':product, 'childproducts':childproducts, 'likes' : likes, 'likeCnt' : likeCnt})

@login_required
def show_myPage(request):
    user = request.user
    myItems_myLevel = MyItem.objects.filter(user=user)
    count = myItems_myLevel.count()
    return render(request,'myPage.html', {'myItems_myLevel':myItems_myLevel, 'count':count})

def submit_myItem_in_myPage(request):
    return render(request, 'sub_Item_myPage.html')

def create_myItem_in_myPage(request):
    try:
        myItems = MyItem()
        myItems.user = request.user
        myItems.itemName = request.GET['itemName']
        myItems.itemShop = request.GET['itemShop']
        myItems.itemDate = request.GET['itemDate']
        myItems.save()
        return redirect('submit_myItem_pop')
    except:
        return redirect('submit_myItem_pop')

def detail_myItem_in_myPage(request, my_Items_id):
    myItems_detail = get_object_or_404(MyItem, pk=my_Items_id)
    if request.user == myItems_detail.user:
        return render(request, 'detail_Item_myPage.html', {'myItems_detail':myItems_detail})
    raise PermissionDenied

def update_myItem_in_myPage(request, my_Items_id):
    myItems_update = get_object_or_404(MyItem, pk=my_Items_id)
    
    if request.user == myItems_update.user:
        if request.method == "POST":
            myItemName = request.POST.get('itemName')
            myItemShop = request.POST.get('itemShop')
            myItemDate = request.POST.get('itemDate')
            myItems_update.itemName = myItemName
            myItems_update.itemShop = myItemShop
            myItems_update.itemDate = myItemDate
            myItems_update.save()
            return redirect('detail_myItem', my_Items_id)
        return render(request, 'update_Item_myPage.html', {'myItems_update':myItems_update})
    raise PermissionDenied

@login_required
def delete_myItem_in_myPage(request, my_Items_id):
    myItems = get_object_or_404(MyItem, pk=my_Items_id)
    if request.user == myItems.user:
        myItems.delete()
        return redirect('mypage')

    raise PermissionDenied


def tip(request):
    tips = Tip.objects.all()
    return render(request, 'tip.html',{'tips':tips})

def tip_detail(request, tip_id):
    tip = get_object_or_404(Tip, pk=tip_id)
    return render(request, 'tip_detail.html', {'tip':tip})

# 좋아요 누르기
@login_required
def like(request, childproduct_id):
    user = request.user
    childproduct = ChildProduct.objects.get(id=childproduct_id)
    product = get_object_or_404(Product, pk = childproduct.product.id)
    likes = Likes.objects.filter(user=user)
    flag = 0 # flag = 1 이면 like에 이미 있다는 뜻. like에서 빼기

    for like in likes:
        if childproduct.id == like.product.id:
            flag = 1
            break
    
    print(flag, "플래그")
    if flag == 1: #삭제
        Likes.objects.filter(user=user, product=childproduct).delete()
        
    else: #추가
        like = Likes.objects.create(user=user, product=childproduct)

    likeCnt = Likes.objects.filter(user=user).count()

    childproduct.save()

    return HttpResponseRedirect(reverse('childproduct', args=[product.id]))
    

# 찜
@login_required
def likeCart(request):
    categories = Category.objects.all()
    likes = Likes.objects.filter(user=request.user)
    totalSum = 0
    for items in likes:
        totalSum = totalSum + 1
   
    return render(request, 'likeCart.html', {'likes' : likes, 'totalSum' : totalSum})

# 찜 삭제
@login_required
def delete_like(request, childproduct_id):
    user = request.user
    likes = Likes.objects.filter(user=request.user)
    likeCnt = Likes.objects.filter(user=user).count()
    quantity = 0
    
    if request.method == 'POST':
        try:
            pk = request.POST.get('product')
            childproduct = ChildProduct.objects.get(pk=pk)
            for i in likes:
                if i.product == childproduct :
                    quantity = quantity + 1
                    print(quantity)
            if quantity > 0 :
                likes = Likes.objects.filter(user=request.user, product_id=pk)
                likes.delete()
                return redirect('likeCart')
        except:
            return redirect('likeCart')

zebraproject/zebraapp/templates/base.html
{% load static %}
{% load django_material_icons %}

<!doctype html>
<html lang="ko-kr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title%}{% endblock %}</title>
    <!-- Css static-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
    />
    <script src="https://kit.fontawesome.com/75e53ee709.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% block link %} {% endblock %}">
    {% block head %} {% endblock %}

</head>

<body>
    <div class="wrapper">
        <!--navbar -->
        <header>
            <div class="nav">

                <a class="logo" href="{%url 'main'%}">
                    <!-- <img src="{% static 'img/logo.svg' %}" width="30" height="30" alt="logo" class="base-img"> -->
                    제로웨이스트 </a>

                <ul class="nav-right">

                    <li><a class="link" href="{% url 'product' 1 %}">SHOP</a></li>

                    {% if user.is_authenticated %}
                    <li><a class="link" href="{% url 'tip' %}">TIP</a></li>
                    <li><img src="{% static 'img/user.png' %}" width="30" height="30" alt="logo" class="user-img">
                        {{user.username}}
                        <ul class="submenu">
                            <li><a class="link" href="{% url 'likeCart' %}">LIKES</a></li>
                            <li><a class="link" href="{% url 'mypage' %}">MY</a></li>
                            <li><a class="link" href="{% url 'logout' %}">LOGOUT</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a class="link" href="{% url 'tip' %}">TIP</a></li>
                    <li><a class="link" href="{% url 'main-login' %}">LOGIN</a></li>
                    {% endif %}

                </ul>
            </div>
        </header>

        {% block content %}
        {% endblock %}
    </div>

    <footer>
        <div class="footer">
            Copyright ⓒ 멋쟁이사자처럼 8기 팀 2DX2. All Rights Reserved.
        </div>
    </footer>
</body>

</html>

zebraproject/zebraapp/templates/childproduct.html
{% extends 'base.html' %}
{% load static %}
{% block title %}쇼핑하기{% endblock %}

{% block link %}{% static 'css/childProduct.css' %}{% endblock %}

{% block content %}
<div class="container">
    <div class="productDetails">
        <img src="{{ product.image.url }}" class="productImg" width="30%" height="30%">
        <h3> {{ product.name }} </h3>
        {% autoescape off %}
        <p class="word-break"> {{ product.detail|linebreaksbr }} </p>
        {% endautoescape %}
    </div>

    <div class="childDetails">
        <table>
            <thead>
                <tr>
                    <th>판매처</th>
                    <th>상품사진</th>
                    <th>상품명</th>
                    <th>판매가</th>
                    <th>배송비</th>
                    <th>찜</th>
                </tr>
            </thead>
            <tbody>

                {% for childproduct in childproducts %}
                <tr>
                    <td>
                        {{childproduct.shopName}}
                    </td>
                    <td>
                        <a href="{{ childproduct.shopLink }}" target="_blank"> <img src="{{ childproduct.image.url }}"
                                class="img" width="100px" height="100px" border-radius="10px" alt="Responsive image">
                        </a>
                    </td>
                    <td>
                        <a href="{{ childproduct.shopLink }}" target="_blank"> {{childproduct.name}} </a>
                    </td>
                    <td>
                        <a href="{{ childproduct.shopLink }}" target="_blank"> {{childproduct.price}}원 </a>
                    </td>
                    <td>
                        {{childproduct.ship}}원
                    </td>
                    <td>
                        {% if user.is_authenticated %}
                            {% if likeCnt == 0 %}
                                <button class="button_mybtn">
                                    <a href="{% url 'productlike' childproduct.id %}" class=""><i
                                            class="material-icons black">favorite</i></a>
                                </button>
                            {% else %}
                                {% if childproduct.likes == 0 %}
                                    <button class="button_mybtn">
                                        <a href="{% url 'productlike' childproduct.id %}" class=""><i
                                                class="material-icons black">favorite</i></a>
                                    </button>
                                {% elif childproduct.likes == 1 %}
                                    <button class="button_mybtn">
                                        <a href="{% url 'productlike' childproduct.id %}" class=""><i
                                                class="material-icons red">favorite</i></a>
                                    </button>
                                {% endif %}
                            {% endif %}
                        {% else %}
                            <button class="button_mybtn" onClick="alertConfirm();location.href='login';">
                                <a href="{% url 'productlike' childproduct.id %}" class=""><i
                                        class="material-icons black">favorite</i></a>
                            </button>
                        {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

            </tbody>
        </table>
    </div>
</div>
<script>
    function alertConfirm() {
        var alertToVisiter = alert('로그인하세요');
        event.preventDefault();

    }
</script>
{% endblock content %}

zebraproject/zebraapp/templates/detail_Item_myPage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}상품 상세페이지{% endblock %}

{% block link %}{% static 'css/mypage_detail.css' %}{% endblock %}

{% block content %}

<div id="wrapper_myItem_detail">
    <section id="detail_wrapper">
    <h2>{{myItems_detail.itemName}}</h2>
    <br>
    구매처 : {{myItems_detail.itemShop}}
    <br><br>
    {{myItems_detail.itemDate|date:"Y M d D"}}
    <br>
    <br>
    <a href="{% url 'update_myItem' myItems_detail.id %}" class="button" id="detail_update_button"><button type="submit" class="btn btn-primary">수정</button></a>
    <a href="{% url 'delete_myItem' myItems_detail.id %}" class="button" id="detail_delete_button"><button type="submit" class="btn btn-primary">삭제</button></a>
    </section>
</div>


{% endblock content %}

zebraproject/zebraapp/templates/likeCart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}쇼핑하기{% endblock %}

{% block link %}{% static 'css/likeCart.css' %}{% endblock %}

{% block content %}
<div class="container">
    <form action="{% url 'delete_like' user.pk %}" method="POST">
        <div class="headTxt">
            <p> 찜한 상품 </p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>판매처</th>
                    <th>상품사진</th>
                    <th>상품명</th>
                    <th>판매가</th>
                    <th>배송비</th>
                    <th>내역 선택</th>
                </tr>
            </thead>
            <tbody>
                {% if totalSum == 0 %}
                <tr>
                    <td class="nothing" colspan="6"><br>찜한 상품이 없어요!<br><br></td>
                </tr>
                {% else %}
                {% for like in likes %}
                <tr>
                    <td>
                        {{like.product.shopName}}
                    </td>
                    <td>
                        <a href="{{ like.product.shopLink }}" target="_blank"> <img src="{{ like.product.image.url }}"
                                class="img" width="100px" height="100px" alt="Responsive image"> </a>
                    </td>
                    <td>
                        <a href="{{ like.product.shopLink }}" target="_blank"> {{like.product.name}} </a>
                    </td>
                    <td>
                        <a href="{{ like.product.shopLink }}" target="_blank"> {{like.product.price}}원 </a>
                    </td>
                    <td>
                        {{like.product.ship}}원
                    </td>
                    <td>
                        <input type="radio" id="{{ like.product.id }}" name="product" value="{{ like.product.id }}">
                    </td>
                </tr>
                {% endfor %}
                {% endif %}

            </tbody>
        </table>
        <br>

        {% if like.quantity == 0 %}
        <button class="button_base mybtn" type="submit" name="delete_like" value="delete_like" onClick="alertConfirm()"> 선택내역 삭제 </button>
        {%else%}
        <button class="button_base mybtn" type="submit" name="delete_like" value="delete_like" onClick="alertDelete()">
            선택내역 삭제 </button>
        {% endif %}

        {% csrf_token %}
    </form>
</div>

<script>
    function alertConfirm() {
        var alertToVisiter = alert('삭제할 항목을 선택해주세요.');
        event.preventDefault();
    }

    function alertDelete() {
        var alertToVisiter = alert('삭제되었습니다.');
        frm.method = "POST";
        frm.submit();
    }
</script>

{% endblock content %}

zebraproject/zebraapp/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block title %}제로웨이스트{% endblock %}

{% block link %}{% static 'css/main.css' %}{% endblock %}

{% block content %}
<img src="{% static 'img/main.png' %}" class="main-img" alt="tip main">
<div class="title-container">
    <p class="title">어서오세요<br>제로웨이스트 플랫폼입니다</p>
</div>
<br>
<div class="img-container">
    <img src="{% static 'img/main1.png' %}" class="sub-img" alt="main">
    {% if user.is_authenticated %}
    <p class="text">{{user.username}}님과 <br> 함께 지구를 지키는 사람들<br> <br>"{{ userCount }}"명</p>
    {% else %}
    <p class="text">제로웨이스트 플랫폼에서 <br> 함께 지구를 지키는 사람들<br> <br>"{{ userCount }}"명</p>
    {% endif %}
</div>
<div class="img-container">
    <img src="{% static 'img/main2.png' %}" class="sub-img" alt="main">
    <p class="text-second">제로 웨이스트:<br>포장을 줄이거나 재활용 가능한 재료를 사용해<br> 쓰레기를 줄이려는 세계적인 움직임</p>
</div>
{% endblock content %}

zebraproject/zebraapp/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 쇼핑하기 {% endblock %}

{% block link %}{% static 'css/product.css' %}{% endblock %}

{% block content %}

<!-- category bar -->
<div class="product_all">
    <ul class="category_bar">
        {% for categories in categories %}
        {% if category == categories %}
        <li class="category_list"><a href="{% url 'product' categories.id %}"
                style="background-color:rgb(151, 128, 116); color:white; border-radius:40px;">{{categories}}</a>
        </li>
        {% else %}
        <li class="category_list"><a href="{% url 'product' categories.id %}">{{categories}}</a></li>
        {% endif %}
        {% endfor %}

    </ul>
</div>

<!-- product 상품 부분 -->

<div class="product-align">
    <div class="product-container">
        {% for post in posts %}
            <figure class="snip1585">
                {% if post.image %}
                <img src="{{post.image.url}}" alt="image">
                {% endif %}
        <figcaption>
            <h3>{{post.name}}</h3>
        </figcaption>
        <a href="{% url 'childproduct' post.id %}"></a>
        </figure>
        {% endfor %}
    </div>
</div>


{% endblock content %}

zebraproject/zebraapp/templates/sub_Item_myPage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}내 상품 등록{% endblock %}

{% block link %}{% static 'css/mypage_submit.css' %}{% endblock %}

{% block content %}

<div id="submit_wrapper">
    <section id="submit_form_wrapper">
        <h1>내가 산 제품 등록</h1>
        <form action="{% url 'create_myItem' %}" id="submit_form">
            <div class="form_wrapper">
                <div class="form_single_wrapper">
                    <label for="input_itemName" id="txt_input_itemName">제품명</label>
                    <input type="text" name="itemName" class="form-control" id="input_item">
                </div>
                <br>
                
                <div class="form_single_wrapper">
                    <label for="input_itemShop" id="txt_input_itemShop">구매처</label>
                    <input type="text" name="itemShop" class="form-control" id="input_item">
                </div>
                <br>
    
                <div class="form_single_wrapper">
                    <label for="input_itemDate" id="txt_input_itemDate">구매일</label>
                    <input type="date" name="itemDate" class="form-control" id="input_item" placeholder="YYYY.MM.DD">
                </div>
                <br>
    
    
                <a class="button" id="submit_button"><button type="submit" class="btn btn-primary" onClick="redirect_mypage()">등록하기</button></a>
                <a class="button" id="close_submit_button"><button type="submit" class="btn btn-primary" onClick="close_popup()">닫기</button></a>
    
    
            </div>
        </form>
    </section>
    
</div>

<!-- '완료'버튼 누르면 팝업창 닫히는 기능 -->
<script>
    function redirect_mypage(){
        window.opener.parent.location.href = "/mypage";
    }

    function close_popup(){
        window.close();
    }
</script>

{% endblock content %}

zebraproject/zebraapp/templates/tip.html
{% extends 'base.html' %}
{% load static %}
{% block title %}팁{% endblock %}

{% block link %}{% static 'css/tip.css' %}{% endblock %}

{% block content %}
<img src="{% static 'img/tip.jpg' %}" class="main-img" alt="tip main">
    <div class="product-align">
    <div class="grid-container">

        {% for tip in tips %}

        <div class="listing">

            <a class="title" href="{% url 'tip_detail' tip.id %}">{{tip.title}}</a>
            <div class="thumbnail-wrappper">
                <div class="thumbnail">
                    <div class="centered">
                        <img src="{{ tip.cover.url }}" class="cover"></a>
                    </div>
                </div>
            </div>

        </div>

        {% endfor %}
    </div>
    </div>

{% endblock content %}

zebraproject/zebraapp/templates/tip_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}팁{% endblock %}

{% block link %}{% static 'css/tip_detail.css' %}{% endblock %}

{% block content %}
<div class="container">
    <div class="title">{{tip.title}}</div>
    <div class="date">{{tip.pub_date|date:"Y년 m월 d일"}}</div>
    <img class="cover" src="{{ tip.cover.url }}" alt="cover">

    {% for body in tip.tipbody_set.all %}

    <img src="{{ body.image.url }}" class="bodyimg" alt="tip-image">
    <div class="body">{{body.body|linebreaksbr}}</div>

    {% endfor %}
</div>
{% endblock content %}

zebraproject/zebraapp/templates/update_Item_myPage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}상품 정보 수정{% endblock %}

{% block link %}{% static 'css/mypage_update.css' %}{% endblock %}

{% block content %} 

<div class="update_wrapper">
    <h1>등록한 제품 수정하기</h1>
    <div class="update_form_wrapper">
        <div class="form_single_wrapper">
            <form action="{% url 'update_myItem' myItems_update.id %}" method="POST" id="update_form">
                {% csrf_token %}
                <label for="input_itemName">제품명</label>
                <input type="text" name="itemName" value="{{myItems_update.itemName}}" class="form-control" id="input_item">
                <br><br>
                <label for="input_itemShop">구매처</label>
                <input type="text" name="itemShop" value="{{myItems_update.itemShop}}" class="form-control" id="input_item">
                <br><br>
                <label for="input_itemDate">구매일</label>
                <input type="date" name="itemDate" value="{{myItems_update.itemDate}}" class="form-control" id="input_item" placeholder="YYYY.MM.DD">
                <br><br>
    
                <a class="button" id="update_button"><button type="submit" class="btn btn-primary">수정하기</button></a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}